//! Transport-agnostic request building.
//!
//! A request model (via `#[derive(MyHttpInput)]`) implements [`THttpRequestBuilder`] and
//! *pushes* its fields straight into the concrete [`crate::UrlBuilder`] and into a headers
//! sink, then hands over its body. A concrete transport — fl-url on native, fetch/gloo on
//! wasm — implements [`HeaderBuilder`] and consumes the returned [`HttpRequestBody`]; the
//! `UrlBuilder` it already shares with `my-http-utils`. Nothing here knows about any transport,
//! so it all compiles under wasm.

use crate::body::HttpRequestBody;
use crate::UrlBuilder;

/// Error produced while building a request — e.g. a field failed its `validator`.
#[derive(Debug, Clone)]
pub struct HttpRequestBuildError {
    pub field: String,
    pub reason: String,
}

impl HttpRequestBuildError {
    pub fn new(field: impl Into<String>, reason: impl Into<String>) -> Self {
        Self {
            field: field.into(),
            reason: reason.into(),
        }
    }
}

impl std::fmt::Display for HttpRequestBuildError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}: {}", self.field, self.reason)
    }
}

impl std::error::Error for HttpRequestBuildError {}

/// Sink for request headers. A transport (e.g. fl-url's header collection) implements this,
/// and the model pushes its header fields directly into it.
pub trait HeaderBuilder {
    fn add_header(&mut self, name: &str, value: &str);
}

/// Supplies randomness for building a request — currently the `multipart/form-data` boundary.
/// The transport/caller implements it for its environment (native RNG on the server/desktop,
/// `crypto.getRandomValues` on wasm), so my-http-utils stays free of any RNG dependency and
/// wasm-safe. A boundary only has to be absent from the body of that one request, so a fresh
/// random string per request is more than enough.
pub trait RandomStringGenerator {
    fn generate_random_string(len: usize) -> String;
}

/// Implemented by a request model (generated by `#[derive(MyHttpInput)]`).
///
/// * [`fill_url`](Self::fill_url) — appends the model's path segments and query params to a
///   [`UrlBuilder`]. The base host (and any static route prefix) are set up by the caller.
/// * [`fill_headers`](Self::fill_headers) — pushes the model's header fields into the sink.
/// * [`get_body`](Self::get_body) — consumes the model and returns its body, so owned bytes
///   (a raw body) move out without cloning.
///
/// Each method applies the field directives (`trim`, `to_lowercase`/`to_uppercase`,
/// `validator`) to the outgoing value and returns [`HttpRequestBuildError`] if a `validator`
/// rejects it. All methods are required — `#[derive(MyHttpInput)]` always generates every one
/// (empty where the model has no such fields), so a model can never silently miss a part.
pub trait THttpRequestBuilder {
    fn fill_url(&self, url_builder: &mut UrlBuilder) -> Result<(), HttpRequestBuildError>;

    fn fill_headers(&self, headers: &mut impl HeaderBuilder) -> Result<(), HttpRequestBuildError>;

    /// Consumes the model and returns its body. The `TRnd` type supplies the random suffix
    /// for a `multipart/form-data` boundary via `TRnd::generate_random_string` (unused for
    /// other body kinds). Call as `model.get_body::<MyRnd>()`.
    #[allow(clippy::extra_unused_type_parameters)] // TRnd is used only by form-data models
    fn get_body<TRnd: RandomStringGenerator>(self) -> Result<HttpRequestBody, HttpRequestBuildError>
    where
        Self: Sized;
}
